import { createFileRoute, Link } from "@tanstack/react-router";
import { AppShell } from "@/components/AppShell";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Mail, FileText, ListChecks, Search, MessageSquare, ArrowRight, Sparkles, AlertTriangle } from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Workplace AI — Productivity Suite" },
      { name: "description", content: "Automate emails, meeting summaries, planning, research and chat with AI." },
    ],
  }),
  component: Dashboard,
});

const tools = [
  { to: "/email", title: "Smart Email Generator", desc: "Draft professional emails in seconds.", icon: Mail },
  { to: "/meetings", title: "Meeting Notes Summarizer", desc: "Turn raw notes into clear summaries.", icon: FileText },
  { to: "/planner", title: "AI Task Planner", desc: "Break goals into prioritized actions.", icon: ListChecks },
  { to: "/research", title: "AI Research Assistant", desc: "Get structured briefings on any topic.", icon: Search },
  { to: "/chatbot", title: "AI Chatbot", desc: "Ask anything, get instant answers.", icon: MessageSquare },
] as const;

function Dashboard() {
  return (
    <AppShell>
      <div className="mx-auto w-full max-w-7xl px-4 py-8 md:px-8 md:py-12">
        <section className="mb-10 overflow-hidden rounded-2xl border border-border bg-gradient-brand p-8 text-primary-foreground shadow-sm md:p-10">
          <div className="flex items-center gap-2 text-xs font-medium uppercase tracking-wider opacity-80">
            <Sparkles className="h-3.5 w-3.5" /> Workplace AI Suite
          </div>
          <h1 className="mt-3 max-w-2xl font-display text-3xl font-semibold leading-tight md:text-4xl">
            Automate the busywork. Spend your day on the work that matters.
          </h1>
          <p className="mt-3 max-w-xl text-sm opacity-90 md:text-base">
            Five AI-powered tools — emails, summaries, planning, research and chat — built into a
            single, focused workspace.
          </p>
        </section>

        <div className="mb-4 flex items-center justify-between">
          <h2 className="text-lg font-semibold">Tools</h2>
          <span className="text-xs text-muted-foreground">{tools.length} workflows ready</span>
        </div>

        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {tools.map((t) => (
            <Link key={t.to} to={t.to} className="group">
              <Card className="h-full transition-all hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-md">
                <CardHeader>
                  <div className="mb-2 flex h-10 w-10 items-center justify-center rounded-lg bg-accent text-accent-foreground">
                    <t.icon className="h-5 w-5" />
                  </div>
                  <CardTitle className="text-base">{t.title}</CardTitle>
                  <CardDescription>{t.desc}</CardDescription>
                </CardHeader>
                <CardContent>
                  <span className="inline-flex items-center gap-1 text-sm font-medium text-primary">
                    Open <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
                  </span>
                </CardContent>
              </Card>
            </Link>
          ))}
        </div>

        <div className="mt-10 flex items-start gap-3 rounded-xl border border-border bg-card p-4 text-sm text-muted-foreground">
          <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
          <p>
            <span className="font-medium text-foreground">Responsible AI:</span> All outputs are
            generated by AI and may be inaccurate or incomplete. Review and edit before sharing,
            and avoid submitting confidential information you wouldn't want processed by a model.
          </p>
        </div>
      </div>
    </AppShell>
  );
}
